### PR TITLE
Use std::chrono

### PR DESCRIPTION
**Pull request by ljbade**
Needed for https://github.com/mapbox/mapbox-gl-native/pull/805

@incanus You mind giving this a quick check?

### CODE REVIEW

**Comment by incanus** [comment]
Yikes, is this really going to be the syntax every time we do an animation? 

```diff
-    mbglMap->setDefaultTransitionDuration(transitionDuration);
+    mbglMap->setDefaultTransitionDuration(std::chrono::duration_cast<std::chrono::steady_clock::duration>(std::chrono::duration<float, std::chrono::seconds::period>(transitionDuration)));
```

We should probably somehow shortcut that? Is there some C++ macro we can use?

**Comment by mikemorris** [comment]
This seems completely unrelated, but I'm hitting
```
Semantic Issue
Unused parameter 'className'
```
at https://github.com/mapbox/mapbox-gl-cocoa/blob/master/mapbox-gl-cocoa/MGLMapView.mm#L1192

Any ideas @incanus?

**Comment by incanus** [comment]
Yeah, not related @mikemorris — this is an on-by-default Clang warning in Xcode for parameters to methods that aren't used in the method body. Safe to ignore right now, but we should either: 

* Remove the warning from defaults (after some discussion)
* "Know better" and wrap in appropriate `#pragma` like https://github.com/mapbox/mapbox-gl-cocoa/blob/2e5bfbdcd54c893864c263b41a27846627e10f0c/mapbox-gl-cocoa/MGLMapView.mm#L476-L500

**Comment by ljbade** [comment]
@incanus I can `typedef` it for you.

**Comment by ljbade** [comment]
@incanus, is it possible to remove the variable's name and just leave the parameter type in Obj-C? This is an easy way to prevent unused warnings in C++

**Comment by incanus** [comment]
> is it possible to remove the variable's name and just leave the parameter type in Obj-C?

Oh neat, maybe! Will look into this.

**Comment by incanus** [comment]
>  I can `typedef` it for you.

Yeah, `typedef` or maybe a postfix operator like how `_millisecond` etc. work could be cool.

**Comment by ljbade** [comment]
@incanus @mikemorris looks like @jfirebaugh is sorting out the build errors: https://github.com/mapbox/mapbox-gl-cocoa/commit/9f18065adefa5bdc6194b93811fbc3b691ac0d6b

**Comment by jfirebaugh** [comment]
Apparently you can't do that in Obj-C:

```
/Users/travis/build/mapbox/mapbox-gl-native/ios/mapbox-gl-cocoa/mapbox-gl-cocoa/MGLMapView.mm:1193:1: error: expected identifier
{
^
1 error generated.
```

https://travis-ci.org/mapbox/mapbox-gl-native/jobs/49361696

@incanus can you look at this?

**Comment by ljbade** [comment]
@jfirebaugh I am testing `#pragma unused()` right now

**Pull request closed without merging**
